# Generated by Django 6.0.3 on 2026-03-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='specs',
        ),
        migrations.AddField(
            model_name='device',
            name='customer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Кому выдан/Продан (ФИО/Компания)'),
        ),
        migrations.AddField(
            model_name='device',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='device',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='devices', max_length=50, verbose_name='Иконка (Material Icon)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена закупки'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('in_stock', 'На складе'), ('issued', 'Выдано/Продано'), ('repair', 'В ремонте'), ('write_off', 'Списано')], default='in_stock', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Название (например, RAM)')),
                ('value', models.CharField(max_length=200, verbose_name='Значение (например, 16GB)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='warehouse.device')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики устройства',
                'ordering': ['key'],
            },
        ),
    ]
