# Generated by Django 6.0.3 on 2026-03-15 07:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_device_specs_device_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Формат: '+99999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Системный лог', 'verbose_name_plural': 'Системные логи'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='device',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='price',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='device',
            name='condition',
            field=models.CharField(choices=[('new', 'Новое'), ('used', 'Б/У'), ('refurbished', 'Восстановленное')], default='new', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='device',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='device',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Для внутреннего учета', max_digits=10, verbose_name='Закупочная цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена продажи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='specs',
            field=models.JSONField(blank=True, default=dict, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='device',
            name='warranty_months',
            field=models.PositiveIntegerField(default=12, verbose_name='Гарантия (мес)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='device-phone-mobile', max_length=50, verbose_name='Иконка (HeroIcon name)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='warehouse.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='IMEI / Серийный номер'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('in_stock', 'На складе'), ('sold', 'Продано'), ('issued', 'Выдано (Аренда)'), ('repair', 'В ремонте')], default='in_stock', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда'), ('return', 'Возврат')], default='sale', max_length=20, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма операции')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='warehouse.client', verbose_name='Клиент')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='warehouse.device', verbose_name='Устройство')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Журнал операций (Продажи)',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
